### ISSUE TITLE
Cannot read properties of undefined (reading 'content') polkadot JSON

### ISSUE THREAD

**Issue by teddyalexy** [polkadot-js/dotapps.io#12]
Trying to restore an account via "add via backup file". Uploaded the json file and received the following error: Cannot read properties of undefined (reading 'content')

So currently unable to access my account and not having the best polkadot experience!

I'm a novice so please be gentle...help!!!

**Comment by jacogr** [comment]
The dotapps.io (ipfs deployment) does not allow local accounts.
